version: "3.3"
services:
  db:
    image: postgres:9.6
    env_file: .docker-env
    expose:
     - "5432"
  hive:
    image: alecharp/the-hive
    depends_on:
      - db
    env_file: .docker-env
    environment:
      - DATABASE_URL=jdbc:postgresql://db/the-hive
    ports:
     - "8181:8080"
